### ISSUE TITLE
Maybe there is a typo

### ISSUE THREAD

**Issue by zhenyuzhang98** [AFD-Illinois/inoisy#2]
Great code, really helpful for my research!

However, I think there is a typo in line 351 of /src/param_general_xy.c.

The last plus should be a multiplication.

**Comment by daelee6** [comment]
Thank you! It's been fixed. It shouldn't have impacted any runs unless explicit time dependence was added to the correlation functions.

**Comment by zhenyuzhang98** [comment]
You're right. Thank you for your reply!
